package mx.edu.uteq.virtual_queue_back.common;

public enum ErrorCode {
	VALIDATION_ERROR,
	RESOURCE_NOT_FOUND,
	UNAUTHORIZED,
	FORBIDDEN,
	CONFLICT,
	DUPLICATE_EMAIL,
	DUPLICATE_USERNAME,
	ACTIVE_TICKET_EXISTS,
	QUEUE_ALREADY_JOINED,
	INVALID_TICKET_TRANSITION,
	QUEUE_NOT_ACTIVE,
	PLACE_NOT_ACTIVE,
	REFRESH_TOKEN_INVALID,
	REFRESH_TOKEN_REUSED,
	COUNTER_NUMBER_REQUIRED,
	COUNTER_ALREADY_CLAIMED,
	COUNTER_CLAIM_REQUIRED,
	INVALID_STAFF_REGISTRATION_KEY,
	STAFF_REGISTRATION_KEY_REQUIRED,
	STAFF_BUSY,
	TICKET_OWNED_BY_OTHER_COUNTER,
	INTERNAL_ERROR
}
