spring.application.name=virtual-queue-back
server.port=8080

spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# TODO: Configurar credenciales de PostgreSQL (spring.datasource.*) y Firebase (ruta al service account JSON) más adelante
